vsphere_vcenter   = "192.168.200.27"
vsphere_server    = "192.168.200.27"
vsphere_user      = "Administrator@vsphere.local"
vsphere_password  = ""
vsphere_datastore = "DS4200-2"
vsphere_cluster   = "CAS"
vsphere_network   = "VM Network"
vm_name           = "web-server12"
vm_cpu_nos        = 2
vm_mem_size       = 4096
#vm_guest_id       = "centos7_64Guest"
vm_disk_label    = "centos7"
vm_template_name = "ubuntu2004"
vm_disk_size     = 80
