variable "vsphere_vcenter" {}
variable "vsphere_server" {}
variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_datastore" {}
variable "vsphere_cluster" {}
variable "vsphere_network" {}
variable "vm_name1" {}
variable "vm_name2" {}
variable "vm_cpu_nos" {}
variable "vm_mem_size" {}
#variable "vm_guest_id" {}
variable "vm_template_name" {}
variable "vm_disk_size" {}
variable "vm_one_disk_label" {}
variable "vm_two_disk_label" {}
